config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations ]

  namespace :api do
    namespace :v2 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
          passwords:          'api/v2/passwords', #'devise_token_auth/passwords',
          omniauth_callbacks: 'devise_token_auth/omniauth_callbacks',
          sessions:           'api/v2/sessions',
          token_validations:  'api/v2/token_validations'
      }
      resources :companies, only: [] do
        collection do
          get 'info', action: :info_company
        end
      end

      resources :employees do
        collection do
          get 'all_by_fecha_de_ingreso'
          get 'all_by_cumpleano_mes'
          get 'all_by_current_month_entry'
          get 'income_and_deductions'
          get 'vacations_enjoy'
          get 'severance_last_months'
          get 'interests_severance_last_months'
          get 'autoservice_files'
          get 'profile'
          get 'basic_info_employees'
          get 'subordinates'
        end
      end

      resources :organization_chart, only:[:index] do
        collection do
          get 'search'
        end
      end

      #consultations
      resources :embargo do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :incapacities do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :payments_deductions do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :indebtedness_level do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :permissions do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :loan_records do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :vacation_balance_records do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :compensatory_vacation_records do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :vacation_record do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end

      #Manager Report
      resources :absences, only: [:show]
      resources :variance_analysis, only: [:show]
      resources :historical_positions, only: [:show]
      resources :historical_salaries, only: [:show]
      resources :staff_turnover , only: [:show]

      resources :articles do
        collection do
          get 'categories',action: :categories_articles
        end
        member do
          put 'viewed'
        end
      end

      resources :comments_articles, only:[:index,:create]

      resources :favorite_employees, only: [:index,:create,:destroy] do
        collection do
          get 'nofavorites/:record/:numrecords',action: :employees_remaining
          get 'favorites/:record/:numrecords',action: :favorites
          post 'search', action: :search
        end
      end

      #Solicitudes y registros

      get 'types_request/:type', to: 'types_request#index'

      resources :requests_employees, only:[:index,:create,:show,:destroy] do
        collection do
          get 'request_states'
          get 'my_requests'
          get 'requests_managed/:record/:numrecords',action: :requests_managed
        end

      end

      resources :approvals, only:[:index,:show,:update]

    end
  end

  root to: "pages#welcome.html"

end

app/controllers/api/v2/employees_controller.rb
class Api::V2::EmployeesController < AuthorizeController

  def subordinates
    authorize! :read, Position
    subordinates = current_user
                       .employee
                       .subordinates
                       .select(:id,:name,:lastname,:id_posicion,:posicion,:image)
                       .order(name: :asc,lastname: :asc)

    subordinates_vacancies = current_user
                                 .employee.my_position
                                 .subordinates_all
                                 .where.not(:id_position => subordinates.pluck(:id_posicion))
                                 .order(name_position: :asc)
    subordinates =  subordinates.as_json(methods:[:amount,:short_name,:type])
    if subordinates_vacancies.present?
      subordinates_vacancies.each do |vacancy|
        subordinates = subordinates.push(organize_vacancies(vacancy))
      end
    end
    @reply = subordinates
    @number_status = 200
  rescue => e
    unless rescue_with_handler(e)
      if Rails.env.development?
        @reply = {status: e.message, details: e.backtrace.inspect }
        @number_status = 202
      else
        Airbrake.notify(e)
        @reply = {}
        @number_status = 500
      end
    end
  ensure
    render json: @reply,status:@number_status
  end


  #Perfil, datos maestros y opciones de llenado
  def profile
    profile_data_basic = (Employee.select([:id,:posicion,:unidad_org,:area,:division_per,:subdivision_per,:name,:lastname]).find_by_id current_user.employee.id).as_json({:methods => :short_name})
    profile = {
        basic_data: profile_data_basic,
        data_master_info: current_user.company.master_datum,
        employee_info: current_user.employee_info
    }
    @reply = profile.as_json
  rescue => e
    rescue_with_handler(e)
  ensure
    render json: @reply,status:@number_status
  end

  #Dias de vacaciones dashboard
  def vacations_enjoy
    begin
      vac_availa = current_user.employee.vacation
      vacation_resume = {
          :value => vac_availa.resumen[2].to_i.to_s
      }
      @reply = vacation_resume.as_json
      @number_status = 200
    rescue => e
      unless rescue_with_handler(e)
        if Rails.env.development?
          @reply = {status: e.message, details: e.backtrace.inspect }
          @number_status = 202
        else
          Airbrake.notify(e)
          @reply = {}
          @number_status = 500
        end
      end
    ensure
      render json: @reply, status: @number_status
    end
  end
  #Mis cesantias dashboard
  def severance_last_months
    begin
      in_sev = current_user.employee.saldo
      saldos_decrypt = {
          :data_graph => eval(in_sev.t_cesantias.to_s),
          :value => in_sev.saldo,
      }
      @number_status =  200
      @reply = saldos_decrypt.as_json
    rescue => e
      unless rescue_with_handler(e)
        if Rails.env.development?
          @reply = {status: e.message, details: e.backtrace.inspect }
          @number_status = 500
        else
          Airbrake.notify(e)
          @reply = {}
          @number_status = 500
        end
      end
    ensure
      render json: @reply, status: @number_status
    end
  end
  #Mis interes de cesantias dashboard
  def interests_severance_last_months
    begin
      in_sev = current_user.employee.saldo
      interests_decrypt = {
          :data_graph => eval(in_sev.t_intcesantias.to_s),
          :value => in_sev.intsaldo,
      }
      @reply = interests_decrypt.as_json
      @number_status = 200
    rescue => e
      unless rescue_with_handler(e)
        if Rails.env.development?
          @reply = {status: e.message, details: e.backtrace.inspect }
          @number_status = 202
        else
          Airbrake.notify(e)
          @reply = {}
          @number_status = 500
        end
      end
    ensure
      render json: @reply, status: @number_status
    end

  end

  #Grafica de ingresos y deducciones
  def income_and_deductions
    begin
      in_ded = current_user.employee.saldo
      saldos_decrypt = {
          :data_graph => eval(in_ded.t_endeudamiento.to_s),
          :total_one => in_ded.totdevengos,
          :total_two => in_ded.totdeducciones,
      }
      @reply = saldos_decrypt.as_json
      @number_status = 200
    rescue => e
      unless rescue_with_handler(e)
        if Rails.env.development?
          @reply = {status: e.message, details: e.backtrace.inspect }
          @number_status = 202
        else
          Airbrake.notify(e)
          @reply = {}
          @number_status = 500
        end
      end
    ensure
      render json: @reply, status: @number_status
    end

  end
  #Ingresos de los ultimos 3 meses
  def all_by_current_month_entry
    t = Time.zone.now
    t2 = t - 3.months

    employees = current_user.company.employees
                    .select('id,name,lastname,image,posicion,fecha_ingreso as date_show')
                    .where('fecha_ingreso <= ?',  t )
                    .where('fecha_ingreso >= ?',  t2 )
                    .order('fecha_ingreso DESC')
    @reply = employees.as_json({:methods => :short_name})
    @number_status = 200

  rescue => e
    rescue_with_handler(e)
  ensure
    render json: @reply,status:@number_status
  end
  # Aniversario de empleados segun su fecha de ingreso un mes por delante
  def all_by_fecha_de_ingreso
    tinitial = Time.zone.now
    tfinal = tinitial+1.months
    employees = current_user.company.employees
                    .select('id,name,lastname,image,posicion,fecha_ingreso as date_show')
                    .where.not(fecha_ingreso:nil)
                    .where( "TO_DATE(concat_ws('-',EXTRACT(YEAR from now()::date+'1 month'::interval),TO_CHAR(fecha_ingreso,'MM-DD')),'YYYY-MM-DD') >= ?", tinitial )
                    .where( "TO_DATE(concat_ws('-',EXTRACT(YEAR from now()::date+'1 month'::interval),TO_CHAR(fecha_ingreso,'MM-DD')),'YYYY-MM-DD') <= ?", tfinal )
                    .order( "TO_DATE(concat_ws('-',EXTRACT(YEAR from NOW()),TO_CHAR(fecha_ingreso,'MM-DD')),'YYYY-MM-DD') ASC" )
    @reply = employees.as_json({:methods => :short_name})
    @number_status = 200
  rescue => e
    rescue_with_handler(e)
  ensure
    render json: @reply,status:@number_status
  end
  # Cumpleaños de empleados del proximo mes al dia de consulta
  def all_by_cumpleano_mes
    tinitial = Date.today
    tfinal = tinitial+1.months

    employees = current_user.company.employees
                    .select('id,name,lastname,image,posicion,fecha_nac as date_show')
                    .where.not(fecha_nac:nil)
                    .where( "TO_DATE(concat_ws('-',EXTRACT(YEAR from now()::date+'1 month'::interval),TO_CHAR(fecha_nac,'MM-DD')),'YYYY-MM-DD') >= ?", tinitial )
                    .where( "TO_DATE(concat_ws('-',EXTRACT(YEAR from now()::date+'1 month'::interval),TO_CHAR(fecha_nac,'MM-DD')),'YYYY-MM-DD') <= ?", tfinal )
                    .order( "TO_DATE(concat_ws('-',EXTRACT(YEAR from NOW()),TO_CHAR(fecha_nac,'MM-DD')),'YYYY-MM-DD') ASC" )
    @reply =  employees.as_json({:methods => :short_name})
    @number_status = 200
  rescue => e
    unless rescue_with_handler(e)
      if Rails.env.development?
        @reply = {status: e.message, details: e.backtrace.inspect }
        @number_status = 202
      else
        Airbrake.notify(e)
        @reply = {}
        @number_status = 500
      end
    end
  ensure
    render json: @reply,status:@number_status
  end

  def autoservice_files
    begin
      pdfs = {}
      pdf_types   = current_user.company.pdf_types
      employee_id = current_user.employee.id

      pdf_types.each do |type|
        files = FileEmployee.select("id, name_iden, file, op, pdf_type_ident, company_id")
                    .where('employee_id = ?', employee_id)
                    .where('op = ?', type.activ)
                    .order('name_iden DESC')

        pdfs[type.activ] = {
            'name' => type.nomid,
            'data' => self.create_files(files)
        }
      end
      @reply = pdfs.to_json
      @number_status = 200
    rescue => e
      unless rescue_with_handler(e)
        if Rails.env.development?
          @reply = {status: e.message, details: e.backtrace.inspect }
          @number_status = 202
        else
          Airbrake.notify(e)
          @reply = {}
          @number_status = 500
        end
      end
    ensure
      render json: @reply, status: @number_status
    end

  end

  protected
  def create_files files
    data = []
    files.each do |file|
      name = file.name_iden == nil ? file.pdf_type.nomid : file.name_iden
      data << {
          :id        => file.id,
          :name_iden => name,
          :file      => {
              :url => file.file.url
          }
      }
    end
    data
  end

  def create_basic_data data, subs
    hp = HistoricalPosition
             .select('position,MIN(begda) as begda,MAX(endda) as endda,MAX(amount_accrued) as amount_accrued,MAX(currency) as currency')
             .where('employee_id = ?' ,data.id)
             .where("endda = ?", "9999-12-31")
             .group('position')

    data = {
        :id => data.id,
        :first_name => data.name.capitalize,
        :last_name => data.lastname.capitalize,
        :name => data.short_name.split.map(&:capitalize).join(' '),
        :position => data.posicion.split.map(&:capitalize).join(' '),
        :area => data.area,
        :amount => hp[0].amount_accrued.to_f,
        :image => {
            :url => data.image.url
        }
    }
    if subs.present? && subs != nil
      data[:subordinates] = subs
    end
    data
  end

  def organize_vacancies(vacancy)
    {
        id: nil,
        name: nil,
        lastname: nil,
        image:nil,
        posicion:vacancy.name_position,
        id_posicion:vacancy.id_position,
        amount:0,
        short_name:t('.vacancy_msg'),
        type:t('.name_vacancy')
    }
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :second_name %><br>
    <%= f.text_field :second_name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :second_lastname %><br>
    <%= f.text_field :second_lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, @users.collect {|s| [s.name, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br>
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :identification %><br>
    <%= f.number_field :identification %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="field">
    <%= f.label :superadmin %><br>
    <%= f.check_box :superadmin %>
  </div>
  <div class="field">
    <%= f.label :apply_reviewer %><br>
    <%= f.number_field :apply_reviewer %>
  </div>
  <div class="field">
    <%= f.label :data_reviewer %><br>
    <%= f.number_field :data_reviewer %>
  </div>
  <div class="field">
    <%= f.label :posicion %><br>
    <%= f.text_field :posicion %>
  </div>
  <div class="field">
    <%= f.label :unidad_org %><br>
    <%= f.text_field :unidad_org %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :division_per %><br>
	<%= f.text_field :division_per %>
  </div>
  <div class="field">
    <%= f.label :subdivision_per %><br>
    <%= f.text_field :subdivision_per %>
  </div>
  <div class="field">
    <%= f.label :moabw %><br>
    <%= f.text_field :moabw %>
  </div>
  <div class="field">
    <%= f.label :see_all_dm %><br>
    <%= f.text_field :see_all_dm %>
  </div>
  <div class="field">
    <%= f.label :see_rpgen %><br>
    <%= f.text_field :see_rpgen %>
  </div>
  <div class="field">
    <%= f.label :see_organ %><br>
    <%= f.text_field :see_organ %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/_form_create.html.erb
<%= form_for(@employee, url: employee_create_employees_path(@employee)) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>	
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :second_name %><br>
    <%= f.text_field :second_name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :second_lastname %><br>
    <%= f.text_field :second_lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, @users.collect {|s| [s.name, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br>
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :identification %><br>
    <%= f.number_field :identification %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="field">
    <%= f.label :superadmin %><br>
    <%= f.check_box :superadmin %>
  </div>
  <div class="field">
    <%= f.label :apply_reviewer %><br>
    <%= f.number_field :apply_reviewer %>
  </div>
  <div class="field">
    <%= f.label :data_reviewer %><br>
    <%= f.number_field :data_reviewer %>
  </div>
  <div class="field">
    <%= f.label :posicion %><br>
    <%= f.text_field :posicion %>
  </div>
  <div class="field">
    <%= f.label :unidad_org %><br>
    <%= f.text_field :unidad_org %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :division_per %><br>
	<%= f.text_field :division_per %>
  </div>
  <div class="field">
    <%= f.label :subdivision_per %><br>
    <%= f.text_field :subdivision_per %>
  </div>
  <div class="field">
    <%= f.label :moabw %><br>
    <%= f.text_field :moabw %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/employee_create.html.erb
<%= @code %>
<%=  @llamada %>
<%=  @description %>
<%=  @headers %>
<%= @error %>

app/views/employees/employee_new.html.erb
<h1>New Employee</h1>

<%= render 'form_create' %>

<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>
	<%= form_tag destroy_multiple_employees_path, method: :delete do %>
<table>
  <thead>
    <tr>
	  <th>Id</th>
	  <th>company_Identification</th>
      <th>Name</th>
      <th>Second name</th>
      <th>Lastname</th>
      <th>Second lastname</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Boss</th>
      <th>User</th>
      <th>Short name</th>
	  <th>Company</th>
      <th>Image</th>
      <th>Admin</th>
      <th>Superadmin</th>
      <th>Apply reviewer</th>
      <th>Data reviewer</th>
      <th>Posicion</th>
		<th>unidad_org</th>
		<th>area</th>
		<th>division_per</th>
		<th>subdivision_per</th>
		<th>moabw</th>
		<th>company_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
		<td>
			<%= check_box_tag "employees[]", employee.id %>
			<%= employee.id %>
		</td>
		<td><%= employee.identification %></td>
        <td><%= employee.name %></td>
        <td><%= employee.second_name %></td>
        <td><%= employee.lastname %></td>
        <td><%= employee.second_lastname %></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.boss %></td>
        <td><%= employee.user_id %></td>
        <td><%= employee.short_name %></td>
		<td><%= employee.company.present? ? employee.company.name : ""  %></td>
		<% if employee.image.present? %>
			<td><%= image_tag employee.image %></td>
		<% end %>
        <td><%= employee.admin %></td>
        <td><%= employee.superadmin %></td>
        <td><%= employee.apply_reviewer %></td>
        <td><%= employee.data_reviewer %></td>
		<td><%= employee.posicion %></td>
		<td><%= employee.unidad_org %></td>
		<td><%= employee.area %></td>
		<td><%= employee.division_per %></td>
		<td><%= employee.subdivision_per %></td>
		<td><%= employee.moabw %></td>
		<td><%= employee.company_id %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td>
			<%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= submit_tag "Delete selected", :class => "button alert" %>
<%= will_paginate @employees %>
<% end %>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/reports.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Cumpleaños">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nombres</Data></Cell>
        <Cell><Data ss:Type="String">Apellidos</Data></Cell>
        <Cell><Data ss:Type="String">Correo</Data></Cell>
        <Cell><Data ss:Type="String">Edad</Data></Cell>
		<Cell><Data ss:Type="String">Fecha de cumpleaños</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de ingreso</Data></Cell>
        <Cell><Data ss:Type="String">Area</Data></Cell>
      </Row>
    <% @employees.each do |user| %>
		<% if user.fecha_nac.present? && user.fecha_nac.month == Time.now.month %>
	      <Row>
	        <Cell><Data ss:Type="String"><%= user.name %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.lastname %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
	        <Cell><Data ss:Type="Number"><%= user.age %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.fecha_nac %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.fecha_ingreso %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.area %></Data></Cell>
	      </Row>
		<% end %>
    <% end %>
    </Table>
  </Worksheet>
  <Worksheet ss:Name="Aniversarios">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nombres</Data></Cell>
        <Cell><Data ss:Type="String">Apellidos</Data></Cell>
        <Cell><Data ss:Type="String">Correo</Data></Cell>
        <Cell><Data ss:Type="String">Antiguedad</Data></Cell>
		<Cell><Data ss:Type="String">Fecha de cumpleaños</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de ingreso</Data></Cell>
        <Cell><Data ss:Type="String">Area</Data></Cell>
      </Row>
    <% @employees.each do |user| %>
		<% if user.fecha_ingreso.present? && user.fecha_ingreso.month == Time.now.month %>
	      <Row>
	        <Cell><Data ss:Type="String"><%= user.name %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.lastname %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
	        <Cell><Data ss:Type="Number"><%= user.antiguedad %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.fecha_nac %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.fecha_ingreso %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.area %></Data></Cell>
	      </Row>
		<% end %>
    <% end %>
    </Table>
  </Worksheet>
  <Worksheet ss:Name="Sesiones">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nombres</Data></Cell>
        <Cell><Data ss:Type="String">Apellidos</Data></Cell>
        <Cell><Data ss:Type="String">Correo</Data></Cell>
        <Cell><Data ss:Type="String">Ultimo ingreso</Data></Cell>
		<Cell><Data ss:Type="String">Fecha de cumpleaños</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de ingreso</Data></Cell>
        <Cell><Data ss:Type="String">Area</Data></Cell>
      </Row>
    <% @employees.each do |user| %>
		<% if user.fecha_ingreso.present? && user.fecha_ingreso.month == Time.now.month %>
	      <Row>
	        <Cell><Data ss:Type="String"><%= user.name %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.lastname %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
          <% if user.user.present? %>
  	        <Cell><Data ss:Type="String"><%= user.user.last_sign_in_at.present? ? 'Hace ' + time_ago_in_words(user.user.last_sign_in_at) : 'No ha ingresado nunca' %></Data></Cell>
          <% else %>
            <Cell><Data ss:Type="String">Usuario no vinculado</Data></Cell>
          <% end %>
          
	        <Cell><Data ss:Type="String"><%= user.fecha_nac %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.fecha_ingreso %></Data></Cell>
	        <Cell><Data ss:Type="String"><%= user.area %></Data></Cell>
	      </Row>
		<% end %>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/employees/show.html.erb
<ul>
<% @employee.attributes.each_pair do |name, value| %>
  <% if name == "image" %>
	  <li> <%= name %>: <%= image_tag value %> </li>
  <% else %>
	  <li> <%= name %>: <strong><%= value %></strong> </li>
  <% end %>
<% end %>
</ul>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>