config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations ]

  namespace :api do
    namespace :v2 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
          passwords:          'api/v2/passwords', #'devise_token_auth/passwords',
          omniauth_callbacks: 'devise_token_auth/omniauth_callbacks',
          sessions:           'api/v2/sessions',
          token_validations:  'api/v2/token_validations'
      }
      resources :companies, only: [] do
        collection do
          get 'info', action: :info_company
        end
      end

      resources :employees do
        collection do
          get 'all_by_fecha_de_ingreso'
          get 'all_by_cumpleano_mes'
          get 'all_by_current_month_entry'
          get 'income_and_deductions'
          get 'vacations_enjoy'
          get 'severance_last_months'
          get 'interests_severance_last_months'
          get 'autoservice_files'
          get 'profile'
          get 'basic_info_employees'
          get 'subordinates'
        end
      end

      resources :organization_chart, only:[:index] do
        collection do
          get 'search'
        end
      end

      #consultations
      resources :embargo do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :incapacities do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :payments_deductions do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :indebtedness_level do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :permissions do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :loan_records do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :vacation_balance_records do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :compensatory_vacation_records do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :vacation_record do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end

      #Manager Report
      resources :absences, only: [:show]
      resources :variance_analysis, only: [:show]
      resources :historical_positions, only: [:show]
      resources :historical_salaries, only: [:show]
      resources :staff_turnover , only: [:show]

      resources :articles do
        collection do
          get 'categories',action: :categories_articles
        end
        member do
          put 'viewed'
        end
      end

      resources :comments_articles, only:[:index,:create]

      resources :favorite_employees, only: [:index,:create,:destroy] do
        collection do
          get 'nofavorites/:record/:numrecords',action: :employees_remaining
          get 'favorites/:record/:numrecords',action: :favorites
          post 'search', action: :search
        end
      end

      #Solicitudes y registros

      get 'types_request/:type', to: 'types_request#index'

      resources :requests_employees, only:[:index,:create,:show,:destroy] do
        collection do
          get 'request_states'
          get 'my_requests'
          get 'requests_managed/:record/:numrecords',action: :requests_managed
        end

      end

      resources :approvals, only:[:index,:show,:update]

    end
  end

  root to: "pages#welcome.html"

end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipos %><br>
    <%= f.text_area :tipos %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Types</h1>

<table>
  <thead>
    <tr>
      <th>Tipos</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.tipos %></td>
        <td><%= type.company.name %>(<%= type.company_id %>)</td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipos:</strong>
  <%= @type.tipos %>
</p>

<p>
  <strong>Company:</strong>
  <%= @type.company %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>