config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations ]

  namespace :api do
    namespace :v2 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
          passwords:          'api/v2/passwords', #'devise_token_auth/passwords',
          omniauth_callbacks: 'devise_token_auth/omniauth_callbacks',
          sessions:           'api/v2/sessions',
          token_validations:  'api/v2/token_validations'
      }
      resources :companies, only: [] do
        collection do
          get 'info', action: :info_company
        end
      end

      resources :employees do
        collection do
          get 'all_by_fecha_de_ingreso'
          get 'all_by_cumpleano_mes'
          get 'all_by_current_month_entry'
          get 'income_and_deductions'
          get 'vacations_enjoy'
          get 'severance_last_months'
          get 'interests_severance_last_months'
          get 'autoservice_files'
          get 'profile'
          get 'basic_info_employees'
          get 'subordinates'
        end
      end

      resources :organization_chart, only:[:index] do
        collection do
          get 'search'
        end
      end

      #consultations
      resources :embargo do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :incapacities do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :payments_deductions do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :indebtedness_level do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :permissions do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :loan_records do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :vacation_balance_records do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :compensatory_vacation_records do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end
      resources :vacation_record do
        collection do
          get 'by_employee/:employee_id', action: :by_employee
        end
      end

      #Manager Report
      resources :absences, only: [:show]
      resources :variance_analysis, only: [:show]
      resources :historical_positions, only: [:show]
      resources :historical_salaries, only: [:show]
      resources :staff_turnover , only: [:show]

      resources :articles do
        collection do
          get 'categories',action: :categories_articles
        end
        member do
          put 'viewed'
        end
      end

      resources :comments_articles, only:[:index,:create]

      resources :favorite_employees, only: [:index,:create,:destroy] do
        collection do
          get 'nofavorites/:record/:numrecords',action: :employees_remaining
          get 'favorites/:record/:numrecords',action: :favorites
          post 'search', action: :search
        end
      end

      #Solicitudes y registros

      get 'types_request/:type', to: 'types_request#index'

      resources :requests_employees, only:[:index,:create,:show,:destroy] do
        collection do
          get 'request_states'
          get 'my_requests'
          get 'requests_managed/:record/:numrecords',action: :requests_managed
        end

      end

      resources :approvals, only:[:index,:show,:update]

    end
  end

  root to: "pages#welcome.html"

end

app/models/company.rb
class Company < ActiveRecord::Base

  crypt_keeper :password_sap,:host_ldap,:username_ldap,:password_ldap,:encryptor => :aes_new, :key => Rails.application.secrets.secret_key_encryption, salt: 'salt', :encoding => 'UTF-8'

  has_many :users, dependent: :destroy
  has_many :employees, dependent: :destroy
  has_many :employee_infos
  has_many :custom_lists
  has_many :articles
  has_many :comments_articles
  has_many :loans
  has_many :severances
  has_many :vacation_requirements
  has_many :compensatory_vacations
  has_many :infos
  has_many :inhability_requirements
  has_many :license_requirements
  has_many :extra_requirements

  has_many :requests_employees
  has_many :labors
  has_many :positions
  has_many :employee_turnovers
  has_many :embargos
  has_many :oauth_applications
  has_many :file_employees
  #Types request
  #has_many :types_requests_records, dependent: :destroy
  has_many :types_request_for_groups

  has_many :pdf_types
  has_one :master_datum

  def total_users_last_months
    company_users   = self.last_mounths_company_user
    total_users     = self.total_employees_or_users company_users, "total_users"
    total_employees = self.total_employees_or_users company_users, "total_employees"
    {users:total_users, employees:total_employees}
  end


  mount_uploader :logo, CompanyImagesUploader
  mount_uploader :logo_dashboard, CompanyImagesUploader
  mount_uploader :logo_inside, CompanyImagesUploader
  mount_uploader :background_login, CompanyImagesUploader
  mount_uploader :background_header_menu, CompanyImagesUploader
  mount_uploader :background_lockscreen, CompanyImagesUploader
  mount_uploader :image_organizate_chart, CompanyImagesUploader
  mount_uploader :name_file_css, CompanyNameFileCssUploader
  mount_uploader :file_translate, CompanyFileTranslateUploader

  protected
  def last_mounths_company_user
    time = Time.zone.now - 5.months
    company_users = CompanyUser.select("extract(year from created_at) as year, extract(month from created_at) as month").distinct
    .where("company_id = ?", self.id)
    .where("created_at >= ?", time)
    .order("year, month asc")
  end

  def total_employees_or_users company_users, field
    total = []
    company_users.each do |value|
      max_users = CompanyUser.select("id, #{field}, extract(year from created_at) as year, extract(month from created_at) as month, created_at")
      .where("company_id = ?", self.id)
      .where("TO_CHAR(created_at, 'YYYY-MM') = ?", "#{value.year.to_i}-#{TaskUtil.number_valid_month(value.month.to_i)}")
      .order("#{field} desc").first
      total << max_users
    end
    total
  end


end

app/controllers/api/v2/companies_controller.rb
class Api::V2::CompaniesController < ApplicationController
  def info_company
    company = Company.select(params_send).find_by_front_domain(request.headers['origin'])
    unless company.present?
      url = request.headers['origin'].gsub('http://','').gsub('https://','').gsub('www','')
      subdomain = url.split('.')[0]
      company = Company.select(params_send).find_by_front_subdomain_and_multiple_domains(subdomain,true)
    end

    render :json => {
        :company => company
    }

  end
  private
  def params_send
    [:id, :logo_dashboard, :logo_inside, :background_login, :background_header_menu, :background_lockscreen, :name_file_css, :primary_color, :text_primary_color,:body_text,:background_wrapper_color ,:login_ldap,:show_birthday,:show_labor,:show_new_employees,:show_articles,:show_certificates_labor,:show_certificates_vacations,:show_certificates_payroll,:show_certificates_income,:show_licenses,:show_loans,:show_vacations,:show_vacations_c,:show_inhabilities,:show_approvals_licenses,:show_services_management,:show_scesa,:show_hoex,:show_approvals_requirements,:show_approvals_master_data,:show_indebtedness_levels,:show_shart_severance,:show_shart_severance_interest,:make_request,:make_approvals,:show_document_management,:show_organizate_chart,:image_organizate_chart]
  end
end

app/helpers/api/v1/companies_helper.rb
module Api::V1::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>
      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :mainurl %><br>
    <%= f.text_field :mainurl %>
  </div>
  <div class="field">
    <%= f.label :sv_cesantias, "Contratación:" %><br>
    <%= f.text_field :sv_cesantias %>
  </div>
  <fieldset>
      <legend>Al dia en pagos</legend>
      <div class="row">
        <div class="large-3 columns">
          <label for="payment">¿Activa?</label>
        </div>
        <div class="large-9 columns">
          <div class="switch">
            <%= f.check_box :active %>
            <%= f.label :active %>
          </div>
        </div>
      </div>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
	  <th>mainurl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
		<td><%= company.mainurl %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
<% @company.attributes.each_pair do |name, value| %>
  <li> <%= name %>: <strong><%= value %></strong> </li>
<% end %>
</ul>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/companies/update_employees.html.erb
<%= @employees %>
<hr />

app/views/companies/update_employees_balances.html.erb
<%= @info %>
<hr />

app/views/companies/update_employees_info.html.erb
<%= @data %>
<hr />
<%= @info %>

app/views/companies/update_labors.html.erb
<h4>Data</h4>
<%= @data %>

app/views/companies/update_selfservices.html.erb
<div class="row">
	<div class="large-12 columns large-centered medium-centered small-centered">
		<%= @data %>
	</div>
</div>

app/views/companies/update_vacations.html.erb
<h4>Vacaciones</h4>
<%= @vacations %>
<hr />
<h4>Data</h4>
<%= @data %>